apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-app-deployment
spec:
  replicas: 1  # Uygulamanızın kaç kopyasını çalıştırmak istediğinizi belirtir
  selector:
    matchLabels:
      app: spark-app
  template:
    metadata:
      labels:
        app: spark-app
    spec:
      containers:
      - name: spark-app-container
        image: kayaozkan/bitirmeprojesi:v1  # Docker Hub’daki imajınız
        ports:
        - containerPort: 8080
